In [1]:
#importing librabries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
#importing both the dataset
dataset_1 = r"C:\Users\Admin\Desktop\CP\Data\raw\Dataset_1.xlsx"
dataset_2 = r"C:\Users\Admin\Desktop\CP\Data\raw\Dataset_2.xlsx"
df_1_hip = pd.read_excel(dataset_1,sheet_name="Hip")
df_1_knee = pd.read_excel(dataset_1,sheet_name="Knee")
df_2 = pd.read_excel(dataset_2,sheet_name='ALL')

In [4]:
hip_angle_column = []
knee_angle_column = []
for i in range(0,1001,20):
    hip_angle_column.append(f"aSagH_pct_GC_{i}")
    knee_angle_column.append(f"aSagK_pct_GC_{i}")
final = hip_angle_column+knee_angle_column
final += ["Patient ID","side",]
df_2 = df_2[final]

In [5]:
df_2

,aSagH_pct_GC_0,aSagH_pct_GC_20,aSagH_pct_GC_40,aSagH_pct_GC_60,aSagH_pct_GC_80,aSagH_pct_GC_100,aSagH_pct_GC_120,aSagH_pct_GC_140,aSagH_pct_GC_160,aSagH_pct_GC_180,...,aSagK_pct_GC_860,aSagK_pct_GC_880,aSagK_pct_GC_900,aSagK_pct_GC_920,aSagK_pct_GC_940,aSagK_pct_GC_960,aSagK_pct_GC_980,aSagK_pct_GC_1000,Patient ID,side
0,36.069069,34.842125,33.163329,31.045698,28.584871,25.976399,23.477484,21.319267,19.627374,18.382525,...,41.198180,37.997094,34.543828,31.148990,28.074550,25.504283,23.517749,22.050743,1,LEFT
1,49.327858,47.586179,46.044471,44.616806,42.944987,40.784168,38.370359,36.210082,34.650712,33.624866,...,72.643572,71.490456,68.210571,62.920801,56.485218,50.319684,45.625430,42.876434,1,RIGHT
2,34.194679,33.296828,32.141047,30.550196,28.629262,26.722533,25.128782,23.948007,23.069861,22.267948,...,50.827850,47.378448,43.298965,38.922902,34.534903,30.361958,26.702895,23.981602,1,LEFT
3,50.962158,49.612400,47.886803,46.089703,44.315857,42.340668,39.958755,37.347298,34.922569,33.009499,...,63.555462,61.464417,58.087269,53.904091,49.693577,46.105064,43.428745,41.652588,1,RIGHT
4,33.203945,31.431343,29.531222,27.611783,25.746723,23.985232,22.371030,20.944492,19.730495,18.726812,...,45.217288,42.260790,39.163257,36.048348,33.069615,30.432156,28.330035,26.820892,1,LEFT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1714,47.469742,46.053108,45.331888,44.581084,42.828897,40.106129,37.668438,36.250913,35.683501,35.284570,...,45.466685,40.409567,35.703524,31.396623,27.461672,24.205176,22.198013,22.002035,357,RIGHT
1715,52.759773,51.803752,50.716878,49.180476,47.829416,47.079990,46.329140,44.716568,42.191752,39.442799,...,42.450990,37.712089,32.741675,27.482991,22.240193,17.676392,15.016614,15.479165,357,LEFT
1716,49.767540,47.656340,45.501696,43.141717,40.612625,38.254464,36.261575,34.456177,32.540390,30.405396,...,48.680881,43.938042,38.640101,33.007701,27.514356,22.853020,19.775416,18.811142,357,RIGHT
1717,37.501434,34.877112,33.788107,33.387425,33.135148,32.940503,32.854687,32.878625,32.923680,32.858463,...,41.368274,43.644795,44.249366,43.567705,40.811301,34.809962,27.145319,21.211102,357,LEFT
1718,38.771809,35.745709,34.001477,33.293910,33.057193,32.857550,32.504282,31.942306,31.151083,30.130272,...,40.365188,39.753864,38.608962,36.353285,32.486267,27.279091,21.798377,17.182608,357,LEFT

In [6]:
# Average per patient per side
df_side_avg = df_2.groupby(['Patient ID', 'side']).mean().reset_index()
import re

def rename_columns(col):
    match = re.match(r'(aSag\w+)_pct_GC_(\d+)', col)
    if match:
        joint, pct = match.groups()
        return f'{joint}_{int(pct) // 10}'
    else:
        return col  # return unchanged if it doesn't match pattern

# Apply to all columns
df_side_avg.rename(columns=rename_columns, inplace=True)

In [7]:
df_side_avg

,Patient ID,side,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,1,LEFT,34.489231,33.190099,31.611866,29.735892,27.653619,25.561388,23.659099,22.070589,...,50.180644,48.361048,45.747773,42.545444,39.002017,35.373413,31.893023,28.766132,26.183560,24.284412
1,1,RIGHT,49.011606,47.744325,46.286800,44.762332,43.128361,41.197440,38.939478,36.635282,...,66.131568,66.850964,66.470237,64.674369,61.338939,56.779394,51.786658,47.293922,43.945390,41.934875
2,2,LEFT,34.472229,33.144917,31.459105,29.866759,28.625891,27.763770,27.147251,26.585736,...,40.571506,46.961723,52.536910,56.208150,57.293242,55.807636,52.560616,48.781184,45.417134,42.779831
3,2,RIGHT,34.115943,33.845007,33.142873,32.425595,31.833842,31.200395,30.316142,29.124648,...,36.856681,41.823153,45.755571,47.958314,48.090432,46.405582,43.682483,40.756274,38.099251,35.805094
4,3,LEFT,40.694482,39.265928,37.703885,36.143189,34.624698,33.116910,31.550782,29.863687,...,55.093501,56.391384,56.186724,54.575575,51.919636,48.754830,45.613230,42.858276,40.645763,38.981412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,355,LEFT,45.973445,45.436610,44.718654,43.733498,42.472684,41.031762,39.463440,37.731146,...,51.425834,46.775414,41.665299,36.420451,31.372851,26.854424,23.175525,20.584527,19.217155,19.053352
686,355,RIGHT,46.193329,45.640961,44.843352,43.599664,41.939730,40.159194,38.464993,36.823626,...,51.891677,48.295267,43.971679,39.210585,34.337921,29.667651,25.504228,22.172570,19.991423,19.161559
687,356,RIGHT,46.184037,44.926099,43.587212,41.911523,40.033367,38.343342,36.932185,35.532516,...,53.595582,49.616682,44.797414,39.500984,34.108604,28.975083,24.389498,20.650562,18.174989,17.351090
688,357,LEFT,46.486619,44.523830,43.204644,42.173792,41.325974,40.658701,40.002343,39.120766,...,44.909197,44.190703,42.903406,41.059792,38.632789,35.602060,31.770724,27.136906,22.715227,19.956616
689,357,RIGHT,48.618641,46.854724,45.416792,43.861400,41.720761,39.180297,36.965007,35.353545,...,55.364538,51.592765,47.073783,42.173804,37.171813,32.202162,27.488014,23.529098,20.986715,20.406589

In [9]:
df_side_avg.to_csv(r"C:\Users\Admin\Desktop\CP\Data\processed\df_side_avg.csv",index=False)#stop

In [166]:
df_1_hip

,ID,Unnamed: 1,% Gait cycle,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,NaN,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
1,NaN,NaN,deg,deg,deg,deg,deg,deg,deg,deg,...,deg,deg,deg,deg,deg,deg,deg,deg,deg,deg
2,CP105,1,51.40882,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,...,49.163118,50.797558,51.933144,52.529213,52.623098,52.340567,51.849561,51.298,50.775906,50.303523
3,CP111,1,37.95706,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.66523,...,34.629051,36.253398,37.575977,38.356998,38.815611,38.855868,38.625624,38.314372,37.774625,36.616468
4,CP113,1,34.543478,33.56814,32.1959,30.524125,28.655009,26.635878,24.472867,22.176569,...,28.547664,29.441454,30.425199,31.549678,32.79621,34.076554,35.257987,36.208715,36.833401,37.077921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,CP152,7,42.429747,40.102682,36.75535,33.408856,30.922122,27.753506,24.640012,21.544426,...,48.029854,50.087994,51.460757,52.091828,51.868722,50.93336,49.537606,47.945812,46.319591,44.377032
193,CP170,7,27.045223,26.06093,25.342578,24.680958,23.506208,21.747387,20.011563,18.636352,...,26.670703,27.998025,28.779883,29.043907,28.909778,28.532628,28.04131,27.457678,26.727102,25.905765
194,CP195,7,43.094113,41.603654,40.014215,38.368341,36.680087,34.948594,33.165763,31.316489,...,40.267146,41.380438,42.260021,42.894325,43.229032,43.189837,42.733435,41.875934,40.678059,39.220403
195,CP83,7,29.389849,28.819173,28.800633,28.806647,28.425304,27.505517,26.08831,24.249631,...,41.451407,42.725803,43.046239,42.082573,39.824615,36.644053,33.214364,30.292191,28.425591,27.751588
196,CP98,7,37.96033,35.169578,32.530529,29.971407,27.42759,24.972638,22.804737,21.064037,...,56.263662,56.89155,56.949103,56.369372,55.10359,53.150503,50.56977,47.483222,44.079028,40.601091

In [167]:
df_1_knee

,ID,Unnamed: 1,% Gait cycle,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52
0,NaN,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
1,NaN,NaN,deg,deg,deg,deg,deg,deg,deg,deg,...,deg,deg,deg,deg,deg,deg,deg,deg,deg,deg
2,CP105,1,18.828689,20.113907,21.913126,23.568939,24.590479,24.764349,24.109085,22.754582,...,51.372876,45.15462,38.591292,32.102879,26.15535,21.22777,17.730555,15.902838,15.736829,16.955275
3,CP111,1,15.530788,16.28742,17.507552,19.152077,20.64307,21.148442,21.393264,21.72192,...,54.33605,48.689244,42.710607,36.123512,29.556417,23.620913,18.96299,16.150704,15.001421,14.935191
4,CP113,1,14.007912,17.427363,20.666071,23.084784,24.51975,25.088658,24.850937,23.778405,...,34.661066,28.846462,23.463793,18.915385,15.39032,12.947345,11.60252,11.357084,12.179563,13.968662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,CP170,7,20.575172,21.646328,20.871593,19.156728,18.559547,16.359543,12.828267,8.77209,...,55.361977,51.864558,47.60437,42.820967,37.69093,32.667078,28.316491,25.181901,23.57328,23.235346
194,CP195,7,10.462818,10.690363,12.401304,14.684606,15.986954,15.73791,15.101613,15.041209,...,45.633593,41.745998,36.806451,31.039062,24.971145,19.29828,14.674303,11.439663,9.590914,9.137108
195,CP83,7,12.58096,12.847924,13.559039,14.339359,14.88418,15.057249,14.866808,14.370401,...,42.732546,37.010111,31.439729,26.273291,21.687163,17.841182,14.871403,12.842567,11.731675,11.424054
196,CP98,7,4.386243,2.551297,1.22838,0.302513,-0.335736,-0.783378,-1.116783,-1.39178,...,22.534464,21.843854,21.268819,20.114453,17.987087,14.978554,11.55247,8.262363,5.531289,3.551057
197,NaN,7,25.68841,23.863716,21.96058,19.508726,16.241434,12.289212,8.168548,4.488471,...,62.372765,59.888309,56.360237,52.000615,47.138596,42.191612,37.577038,33.588429,30.319975,27.675149

In [168]:
knee_col = list(df_1_knee.iloc[0])
knee_col.pop(0)
knee_col.insert(0,"ID")
knee_col

['ID',
 'Pattern',
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [169]:
df_1_knee.columns = knee_col

In [170]:
df_1_knee

,ID,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
0,NaN,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
1,NaN,NaN,deg,deg,deg,deg,deg,deg,deg,deg,...,deg,deg,deg,deg,deg,deg,deg,deg,deg,deg
2,CP105,1,18.828689,20.113907,21.913126,23.568939,24.590479,24.764349,24.109085,22.754582,...,51.372876,45.15462,38.591292,32.102879,26.15535,21.22777,17.730555,15.902838,15.736829,16.955275
3,CP111,1,15.530788,16.28742,17.507552,19.152077,20.64307,21.148442,21.393264,21.72192,...,54.33605,48.689244,42.710607,36.123512,29.556417,23.620913,18.96299,16.150704,15.001421,14.935191
4,CP113,1,14.007912,17.427363,20.666071,23.084784,24.51975,25.088658,24.850937,23.778405,...,34.661066,28.846462,23.463793,18.915385,15.39032,12.947345,11.60252,11.357084,12.179563,13.968662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,CP170,7,20.575172,21.646328,20.871593,19.156728,18.559547,16.359543,12.828267,8.77209,...,55.361977,51.864558,47.60437,42.820967,37.69093,32.667078,28.316491,25.181901,23.57328,23.235346
194,CP195,7,10.462818,10.690363,12.401304,14.684606,15.986954,15.73791,15.101613,15.041209,...,45.633593,41.745998,36.806451,31.039062,24.971145,19.29828,14.674303,11.439663,9.590914,9.137108
195,CP83,7,12.58096,12.847924,13.559039,14.339359,14.88418,15.057249,14.866808,14.370401,...,42.732546,37.010111,31.439729,26.273291,21.687163,17.841182,14.871403,12.842567,11.731675,11.424054
196,CP98,7,4.386243,2.551297,1.22838,0.302513,-0.335736,-0.783378,-1.116783,-1.39178,...,22.534464,21.843854,21.268819,20.114453,17.987087,14.978554,11.55247,8.262363,5.531289,3.551057
197,NaN,7,25.68841,23.863716,21.96058,19.508726,16.241434,12.289212,8.168548,4.488471,...,62.372765,59.888309,56.360237,52.000615,47.138596,42.191612,37.577038,33.588429,30.319975,27.675149

In [171]:
df_1_knee = df_1_knee.drop([0,1])
df_1_knee.reset_index(drop=True)

,ID,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
0,CP105,1,18.828689,20.113907,21.913126,23.568939,24.590479,24.764349,24.109085,22.754582,...,51.372876,45.15462,38.591292,32.102879,26.15535,21.22777,17.730555,15.902838,15.736829,16.955275
1,CP111,1,15.530788,16.28742,17.507552,19.152077,20.64307,21.148442,21.393264,21.72192,...,54.33605,48.689244,42.710607,36.123512,29.556417,23.620913,18.96299,16.150704,15.001421,14.935191
2,CP113,1,14.007912,17.427363,20.666071,23.084784,24.51975,25.088658,24.850937,23.778405,...,34.661066,28.846462,23.463793,18.915385,15.39032,12.947345,11.60252,11.357084,12.179563,13.968662
3,CP127,1,10.606166,11.512478,14.157871,18.428616,19.932304,19.500035,18.827945,17.222503,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.84174,10.075318,10.333831
4,CP157,1,17.245873,19.780524,22.585412,24.028705,24.27663,25.130417,26.171021,25.942289,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.70376,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,CP170,7,20.575172,21.646328,20.871593,19.156728,18.559547,16.359543,12.828267,8.77209,...,55.361977,51.864558,47.60437,42.820967,37.69093,32.667078,28.316491,25.181901,23.57328,23.235346
192,CP195,7,10.462818,10.690363,12.401304,14.684606,15.986954,15.73791,15.101613,15.041209,...,45.633593,41.745998,36.806451,31.039062,24.971145,19.29828,14.674303,11.439663,9.590914,9.137108
193,CP83,7,12.58096,12.847924,13.559039,14.339359,14.88418,15.057249,14.866808,14.370401,...,42.732546,37.010111,31.439729,26.273291,21.687163,17.841182,14.871403,12.842567,11.731675,11.424054
194,CP98,7,4.386243,2.551297,1.22838,0.302513,-0.335736,-0.783378,-1.116783,-1.39178,...,22.534464,21.843854,21.268819,20.114453,17.987087,14.978554,11.55247,8.262363,5.531289,3.551057
195,NaN,7,25.68841,23.863716,21.96058,19.508726,16.241434,12.289212,8.168548,4.488471,...,62.372765,59.888309,56.360237,52.000615,47.138596,42.191612,37.577038,33.588429,30.319975,27.675149

In [172]:
df_1_knee = df_1_knee.iloc[:-1]
df_1_knee.reset_index(drop=True)

,ID,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
0,CP105,1,18.828689,20.113907,21.913126,23.568939,24.590479,24.764349,24.109085,22.754582,...,51.372876,45.15462,38.591292,32.102879,26.15535,21.22777,17.730555,15.902838,15.736829,16.955275
1,CP111,1,15.530788,16.28742,17.507552,19.152077,20.64307,21.148442,21.393264,21.72192,...,54.33605,48.689244,42.710607,36.123512,29.556417,23.620913,18.96299,16.150704,15.001421,14.935191
2,CP113,1,14.007912,17.427363,20.666071,23.084784,24.51975,25.088658,24.850937,23.778405,...,34.661066,28.846462,23.463793,18.915385,15.39032,12.947345,11.60252,11.357084,12.179563,13.968662
3,CP127,1,10.606166,11.512478,14.157871,18.428616,19.932304,19.500035,18.827945,17.222503,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.84174,10.075318,10.333831
4,CP157,1,17.245873,19.780524,22.585412,24.028705,24.27663,25.130417,26.171021,25.942289,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.70376,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,CP152,7,24.487148,23.662027,24.864199,24.523369,21.072299,17.905445,14.897992,11.010249,...,55.231592,53.383502,50.746365,47.185969,42.841141,37.997811,33.205888,28.943379,25.48404,22.766658
191,CP170,7,20.575172,21.646328,20.871593,19.156728,18.559547,16.359543,12.828267,8.77209,...,55.361977,51.864558,47.60437,42.820967,37.69093,32.667078,28.316491,25.181901,23.57328,23.235346
192,CP195,7,10.462818,10.690363,12.401304,14.684606,15.986954,15.73791,15.101613,15.041209,...,45.633593,41.745998,36.806451,31.039062,24.971145,19.29828,14.674303,11.439663,9.590914,9.137108
193,CP83,7,12.58096,12.847924,13.559039,14.339359,14.88418,15.057249,14.866808,14.370401,...,42.732546,37.010111,31.439729,26.273291,21.687163,17.841182,14.871403,12.842567,11.731675,11.424054
194,CP98,7,4.386243,2.551297,1.22838,0.302513,-0.335736,-0.783378,-1.116783,-1.39178,...,22.534464,21.843854,21.268819,20.114453,17.987087,14.978554,11.55247,8.262363,5.531289,3.551057

In [173]:
hip_col = list(df_1_hip.iloc[0])
hip_col.pop(0)
hip_col.insert(0,"ID")
hip_col

['ID',
 'Pattern',
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [174]:
df_1_hip.columns = hip_col

In [175]:
df_1_hip

,ID,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
0,NaN,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
1,NaN,NaN,deg,deg,deg,deg,deg,deg,deg,deg,...,deg,deg,deg,deg,deg,deg,deg,deg,deg,deg
2,CP105,1,51.40882,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,...,49.163118,50.797558,51.933144,52.529213,52.623098,52.340567,51.849561,51.298,50.775906,50.303523
3,CP111,1,37.95706,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.66523,...,34.629051,36.253398,37.575977,38.356998,38.815611,38.855868,38.625624,38.314372,37.774625,36.616468
4,CP113,1,34.543478,33.56814,32.1959,30.524125,28.655009,26.635878,24.472867,22.176569,...,28.547664,29.441454,30.425199,31.549678,32.79621,34.076554,35.257987,36.208715,36.833401,37.077921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,CP152,7,42.429747,40.102682,36.75535,33.408856,30.922122,27.753506,24.640012,21.544426,...,48.029854,50.087994,51.460757,52.091828,51.868722,50.93336,49.537606,47.945812,46.319591,44.377032
193,CP170,7,27.045223,26.06093,25.342578,24.680958,23.506208,21.747387,20.011563,18.636352,...,26.670703,27.998025,28.779883,29.043907,28.909778,28.532628,28.04131,27.457678,26.727102,25.905765
194,CP195,7,43.094113,41.603654,40.014215,38.368341,36.680087,34.948594,33.165763,31.316489,...,40.267146,41.380438,42.260021,42.894325,43.229032,43.189837,42.733435,41.875934,40.678059,39.220403
195,CP83,7,29.389849,28.819173,28.800633,28.806647,28.425304,27.505517,26.08831,24.249631,...,41.451407,42.725803,43.046239,42.082573,39.824615,36.644053,33.214364,30.292191,28.425591,27.751588
196,CP98,7,37.96033,35.169578,32.530529,29.971407,27.42759,24.972638,22.804737,21.064037,...,56.263662,56.89155,56.949103,56.369372,55.10359,53.150503,50.56977,47.483222,44.079028,40.601091

In [176]:
df_1_hip = df_1_hip.drop([0,1])
df_1_hip.reset_index(drop=True)

,ID,Pattern,0,2,4,6,8,10,12,14,...,82,84,86,88,90,92,94,96,98,100
0,CP105,1,51.40882,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,...,49.163118,50.797558,51.933144,52.529213,52.623098,52.340567,51.849561,51.298,50.775906,50.303523
1,CP111,1,37.95706,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.66523,...,34.629051,36.253398,37.575977,38.356998,38.815611,38.855868,38.625624,38.314372,37.774625,36.616468
2,CP113,1,34.543478,33.56814,32.1959,30.524125,28.655009,26.635878,24.472867,22.176569,...,28.547664,29.441454,30.425199,31.549678,32.79621,34.076554,35.257987,36.208715,36.833401,37.077921
3,CP127,1,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,...,35.343323,36.733593,37.544657,38.111085,38.204016,37.918152,37.517561,37.11613,36.475946,35.641003
4,CP157,1,34.1972,35.312177,36.060747,35.624389,34.566009,33.64915,32.641324,31.035173,...,28.878215,30.753307,32.000382,32.601669,32.675271,32.434948,32.089461,31.833217,31.933858,32.635316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,CP152,7,42.429747,40.102682,36.75535,33.408856,30.922122,27.753506,24.640012,21.544426,...,48.029854,50.087994,51.460757,52.091828,51.868722,50.93336,49.537606,47.945812,46.319591,44.377032
191,CP170,7,27.045223,26.06093,25.342578,24.680958,23.506208,21.747387,20.011563,18.636352,...,26.670703,27.998025,28.779883,29.043907,28.909778,28.532628,28.04131,27.457678,26.727102,25.905765
192,CP195,7,43.094113,41.603654,40.014215,38.368341,36.680087,34.948594,33.165763,31.316489,...,40.267146,41.380438,42.260021,42.894325,43.229032,43.189837,42.733435,41.875934,40.678059,39.220403
193,CP83,7,29.389849,28.819173,28.800633,28.806647,28.425304,27.505517,26.08831,24.249631,...,41.451407,42.725803,43.046239,42.082573,39.824615,36.644053,33.214364,30.292191,28.425591,27.751588
194,CP98,7,37.96033,35.169578,32.530529,29.971407,27.42759,24.972638,22.804737,21.064037,...,56.263662,56.89155,56.949103,56.369372,55.10359,53.150503,50.56977,47.483222,44.079028,40.601091

In [177]:
hip_angle_name = []
knee_angle_name = []

for i in range(0,101,2):
    hip_angle_name.append(f"aSagH_{i}")
    knee_angle_name.append(f"aSagK_{i}")

In [178]:
hip_angle_name.insert(0,"ID")
hip_angle_name.insert(1,"Pattern")
hip_angle_name

['ID',
 'Pattern',
 'aSagH_0',
 'aSagH_2',
 'aSagH_4',
 'aSagH_6',
 'aSagH_8',
 'aSagH_10',
 'aSagH_12',
 'aSagH_14',
 'aSagH_16',
 'aSagH_18',
 'aSagH_20',
 'aSagH_22',
 'aSagH_24',
 'aSagH_26',
 'aSagH_28',
 'aSagH_30',
 'aSagH_32',
 'aSagH_34',
 'aSagH_36',
 'aSagH_38',
 'aSagH_40',
 'aSagH_42',
 'aSagH_44',
 'aSagH_46',
 'aSagH_48',
 'aSagH_50',
 'aSagH_52',
 'aSagH_54',
 'aSagH_56',
 'aSagH_58',
 'aSagH_60',
 'aSagH_62',
 'aSagH_64',
 'aSagH_66',
 'aSagH_68',
 'aSagH_70',
 'aSagH_72',
 'aSagH_74',
 'aSagH_76',
 'aSagH_78',
 'aSagH_80',
 'aSagH_82',
 'aSagH_84',
 'aSagH_86',
 'aSagH_88',
 'aSagH_90',
 'aSagH_92',
 'aSagH_94',
 'aSagH_96',
 'aSagH_98',
 'aSagH_100']

In [179]:
knee_angle_name.insert(0,"ID")
knee_angle_name.insert(1,"Pattern")
knee_angle_name

['ID',
 'Pattern',
 'aSagK_0',
 'aSagK_2',
 'aSagK_4',
 'aSagK_6',
 'aSagK_8',
 'aSagK_10',
 'aSagK_12',
 'aSagK_14',
 'aSagK_16',
 'aSagK_18',
 'aSagK_20',
 'aSagK_22',
 'aSagK_24',
 'aSagK_26',
 'aSagK_28',
 'aSagK_30',
 'aSagK_32',
 'aSagK_34',
 'aSagK_36',
 'aSagK_38',
 'aSagK_40',
 'aSagK_42',
 'aSagK_44',
 'aSagK_46',
 'aSagK_48',
 'aSagK_50',
 'aSagK_52',
 'aSagK_54',
 'aSagK_56',
 'aSagK_58',
 'aSagK_60',
 'aSagK_62',
 'aSagK_64',
 'aSagK_66',
 'aSagK_68',
 'aSagK_70',
 'aSagK_72',
 'aSagK_74',
 'aSagK_76',
 'aSagK_78',
 'aSagK_80',
 'aSagK_82',
 'aSagK_84',
 'aSagK_86',
 'aSagK_88',
 'aSagK_90',
 'aSagK_92',
 'aSagK_94',
 'aSagK_96',
 'aSagK_98',
 'aSagK_100']

In [180]:
df_1_hip.columns = hip_angle_name
df_1_knee.columns = knee_angle_name

In [181]:
df_1_knee

,ID,Pattern,aSagK_0,aSagK_2,aSagK_4,aSagK_6,aSagK_8,aSagK_10,aSagK_12,aSagK_14,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
2,CP105,1,18.828689,20.113907,21.913126,23.568939,24.590479,24.764349,24.109085,22.754582,...,51.372876,45.15462,38.591292,32.102879,26.15535,21.22777,17.730555,15.902838,15.736829,16.955275
3,CP111,1,15.530788,16.28742,17.507552,19.152077,20.64307,21.148442,21.393264,21.72192,...,54.33605,48.689244,42.710607,36.123512,29.556417,23.620913,18.96299,16.150704,15.001421,14.935191
4,CP113,1,14.007912,17.427363,20.666071,23.084784,24.51975,25.088658,24.850937,23.778405,...,34.661066,28.846462,23.463793,18.915385,15.39032,12.947345,11.60252,11.357084,12.179563,13.968662
5,CP127,1,10.606166,11.512478,14.157871,18.428616,19.932304,19.500035,18.827945,17.222503,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.84174,10.075318,10.333831
6,CP157,1,17.245873,19.780524,22.585412,24.028705,24.27663,25.130417,26.171021,25.942289,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.70376,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,CP152,7,24.487148,23.662027,24.864199,24.523369,21.072299,17.905445,14.897992,11.010249,...,55.231592,53.383502,50.746365,47.185969,42.841141,37.997811,33.205888,28.943379,25.48404,22.766658
193,CP170,7,20.575172,21.646328,20.871593,19.156728,18.559547,16.359543,12.828267,8.77209,...,55.361977,51.864558,47.60437,42.820967,37.69093,32.667078,28.316491,25.181901,23.57328,23.235346
194,CP195,7,10.462818,10.690363,12.401304,14.684606,15.986954,15.73791,15.101613,15.041209,...,45.633593,41.745998,36.806451,31.039062,24.971145,19.29828,14.674303,11.439663,9.590914,9.137108
195,CP83,7,12.58096,12.847924,13.559039,14.339359,14.88418,15.057249,14.866808,14.370401,...,42.732546,37.010111,31.439729,26.273291,21.687163,17.841182,14.871403,12.842567,11.731675,11.424054
196,CP98,7,4.386243,2.551297,1.22838,0.302513,-0.335736,-0.783378,-1.116783,-1.39178,...,22.534464,21.843854,21.268819,20.114453,17.987087,14.978554,11.55247,8.262363,5.531289,3.551057

In [182]:
df_1_hip

,ID,Pattern,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,...,aSagH_82,aSagH_84,aSagH_86,aSagH_88,aSagH_90,aSagH_92,aSagH_94,aSagH_96,aSagH_98,aSagH_100
2,CP105,1,51.40882,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,...,49.163118,50.797558,51.933144,52.529213,52.623098,52.340567,51.849561,51.298,50.775906,50.303523
3,CP111,1,37.95706,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.66523,...,34.629051,36.253398,37.575977,38.356998,38.815611,38.855868,38.625624,38.314372,37.774625,36.616468
4,CP113,1,34.543478,33.56814,32.1959,30.524125,28.655009,26.635878,24.472867,22.176569,...,28.547664,29.441454,30.425199,31.549678,32.79621,34.076554,35.257987,36.208715,36.833401,37.077921
5,CP127,1,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,...,35.343323,36.733593,37.544657,38.111085,38.204016,37.918152,37.517561,37.11613,36.475946,35.641003
6,CP157,1,34.1972,35.312177,36.060747,35.624389,34.566009,33.64915,32.641324,31.035173,...,28.878215,30.753307,32.000382,32.601669,32.675271,32.434948,32.089461,31.833217,31.933858,32.635316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,CP152,7,42.429747,40.102682,36.75535,33.408856,30.922122,27.753506,24.640012,21.544426,...,48.029854,50.087994,51.460757,52.091828,51.868722,50.93336,49.537606,47.945812,46.319591,44.377032
193,CP170,7,27.045223,26.06093,25.342578,24.680958,23.506208,21.747387,20.011563,18.636352,...,26.670703,27.998025,28.779883,29.043907,28.909778,28.532628,28.04131,27.457678,26.727102,25.905765
194,CP195,7,43.094113,41.603654,40.014215,38.368341,36.680087,34.948594,33.165763,31.316489,...,40.267146,41.380438,42.260021,42.894325,43.229032,43.189837,42.733435,41.875934,40.678059,39.220403
195,CP83,7,29.389849,28.819173,28.800633,28.806647,28.425304,27.505517,26.08831,24.249631,...,41.451407,42.725803,43.046239,42.082573,39.824615,36.644053,33.214364,30.292191,28.425591,27.751588
196,CP98,7,37.96033,35.169578,32.530529,29.971407,27.42759,24.972638,22.804737,21.064037,...,56.263662,56.89155,56.949103,56.369372,55.10359,53.150503,50.56977,47.483222,44.079028,40.601091

In [183]:
df_1_hip = df_1_hip.drop("Pattern",axis=1)
df_1_hip.reset_index(drop=True)

,ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagH_82,aSagH_84,aSagH_86,aSagH_88,aSagH_90,aSagH_92,aSagH_94,aSagH_96,aSagH_98,aSagH_100
0,CP105,51.40882,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,39.300897,...,49.163118,50.797558,51.933144,52.529213,52.623098,52.340567,51.849561,51.298,50.775906,50.303523
1,CP111,37.95706,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.66523,23.454627,...,34.629051,36.253398,37.575977,38.356998,38.815611,38.855868,38.625624,38.314372,37.774625,36.616468
2,CP113,34.543478,33.56814,32.1959,30.524125,28.655009,26.635878,24.472867,22.176569,19.786189,...,28.547664,29.441454,30.425199,31.549678,32.79621,34.076554,35.257987,36.208715,36.833401,37.077921
3,CP127,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,27.657092,...,35.343323,36.733593,37.544657,38.111085,38.204016,37.918152,37.517561,37.11613,36.475946,35.641003
4,CP157,34.1972,35.312177,36.060747,35.624389,34.566009,33.64915,32.641324,31.035173,28.675158,...,28.878215,30.753307,32.000382,32.601669,32.675271,32.434948,32.089461,31.833217,31.933858,32.635316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,CP152,42.429747,40.102682,36.75535,33.408856,30.922122,27.753506,24.640012,21.544426,18.561348,...,48.029854,50.087994,51.460757,52.091828,51.868722,50.93336,49.537606,47.945812,46.319591,44.377032
191,CP170,27.045223,26.06093,25.342578,24.680958,23.506208,21.747387,20.011563,18.636352,17.367513,...,26.670703,27.998025,28.779883,29.043907,28.909778,28.532628,28.04131,27.457678,26.727102,25.905765
192,CP195,43.094113,41.603654,40.014215,38.368341,36.680087,34.948594,33.165763,31.316489,29.379185,...,40.267146,41.380438,42.260021,42.894325,43.229032,43.189837,42.733435,41.875934,40.678059,39.220403
193,CP83,29.389849,28.819173,28.800633,28.806647,28.425304,27.505517,26.08831,24.249631,22.013928,...,41.451407,42.725803,43.046239,42.082573,39.824615,36.644053,33.214364,30.292191,28.425591,27.751588
194,CP98,37.96033,35.169578,32.530529,29.971407,27.42759,24.972638,22.804737,21.064037,19.682343,...,56.263662,56.89155,56.949103,56.369372,55.10359,53.150503,50.56977,47.483222,44.079028,40.601091

In [184]:
df_1_knee = df_1_knee.drop("Pattern",axis=1)
df_1_knee = df_1_knee.reset_index(drop=True)

In [185]:
df_1_knee.to_csv(r"C:\Users\Admin\Desktop\CP\Data\processed\df_1_knee.csv",index=False)
df_1_knee.to_excel(r"C:\Users\Admin\Desktop\CP\Data\processed\df_1_knee.xlsx",index=False)

In [186]:
df_1_hip.to_csv(r"C:\Users\Admin\Desktop\CP\Data\processed\df_1_hip.csv",index=False)
df_1_hip.to_excel(r"C:\Users\Admin\Desktop\CP\Data\processed\df_1_hip.xlsx",index=False)

In [187]:
merged_df = pd.merge(df_1_hip,df_1_knee)

In [188]:
merged_df

,ID,aSagH_0,aSagH_2,aSagH_4,aSagH_6,aSagH_8,aSagH_10,aSagH_12,aSagH_14,aSagH_16,...,aSagK_82,aSagK_84,aSagK_86,aSagK_88,aSagK_90,aSagK_92,aSagK_94,aSagK_96,aSagK_98,aSagK_100
0,CP105,51.40882,50.933351,50.243717,49.185245,47.719346,45.910284,43.859224,41.645014,39.300897,...,51.372876,45.15462,38.591292,32.102879,26.15535,21.22777,17.730555,15.902838,15.736829,16.955275
1,CP111,37.95706,36.832004,35.150579,33.196743,31.149266,29.142866,27.296597,25.66523,23.454627,...,54.33605,48.689244,42.710607,36.123512,29.556417,23.620913,18.96299,16.150704,15.001421,14.935191
2,CP113,34.543478,33.56814,32.1959,30.524125,28.655009,26.635878,24.472867,22.176569,19.786189,...,34.661066,28.846462,23.463793,18.915385,15.39032,12.947345,11.60252,11.357084,12.179563,13.968662
3,CP127,39.280994,37.954086,37.565979,37.898317,36.484441,34.009033,31.881341,29.772771,27.657092,...,38.296512,33.717704,28.803688,23.955544,19.446595,15.524868,12.601406,10.84174,10.075318,10.333831
4,CP157,34.1972,35.312177,36.060747,35.624389,34.566009,33.64915,32.641324,31.035173,28.675158,...,61.099208,57.061305,51.597262,44.833063,37.268508,29.70376,22.975866,17.964445,15.561585,16.119956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,CP152,42.429747,40.102682,36.75535,33.408856,30.922122,27.753506,24.640012,21.544426,18.561348,...,55.231592,53.383502,50.746365,47.185969,42.841141,37.997811,33.205888,28.943379,25.48404,22.766658
191,CP170,27.045223,26.06093,25.342578,24.680958,23.506208,21.747387,20.011563,18.636352,17.367513,...,55.361977,51.864558,47.60437,42.820967,37.69093,32.667078,28.316491,25.181901,23.57328,23.235346
192,CP195,43.094113,41.603654,40.014215,38.368341,36.680087,34.948594,33.165763,31.316489,29.379185,...,45.633593,41.745998,36.806451,31.039062,24.971145,19.29828,14.674303,11.439663,9.590914,9.137108
193,CP83,29.389849,28.819173,28.800633,28.806647,28.425304,27.505517,26.08831,24.249631,22.013928,...,42.732546,37.010111,31.439729,26.273291,21.687163,17.841182,14.871403,12.842567,11.731675,11.424054
194,CP98,37.96033,35.169578,32.530529,29.971407,27.42759,24.972638,22.804737,21.064037,19.682343,...,22.534464,21.843854,21.268819,20.114453,17.987087,14.978554,11.55247,8.262363,5.531289,3.551057

In [189]:
merged_df.to_csv(r"C:\Users\Admin\Desktop\CP\Data\processed\merged_df.csv",index=False)
merged_df.to_excel(r"C:\Users\Admin\Desktop\CP\Data\processed\merged_df.xlsx",index=False)